# Generated by Django 5.1.6 on 2025-02-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('plot_summary', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
